### ISSUE TITLE
IDEA internal verion 233.13135.103 compatible exception

### ISSUE THREAD

**Issue by CoolLoong** [TSergey/intellij-javadocs#111]
Plugin 'JavaDoc' (version '4.1.0') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is IU-233.13135.103

**Comment by rainzhou2012** [comment]
The same issue.

**Comment by TSergey** [comment]
Updated plugin for compatibility for Intellij 2023.3. Updated plugin version is 4.1.1
