### ISSUE TITLE
Releases after 4.0.2 are incompatible with 2024.1

### ISSUE THREAD

**Issue by ShrykeWindgrace** [TSergey/intellij-javadocs#115]
E.g. the the version `4.1.1` has the following line in its `plugin.xml`:

```xml
<idea-version since-build="233.11799" until-build="233.*" />
```
The latest version of the plugin compatible with 2024.1 IDEs is, surprisingly, `4.0.2`, and that's quite old.

Plugin's page on Marketplace shows the same version constraints: https://plugins.jetbrains.com/plugin/7157-javadoc/versions/stable

**Comment by TSergey** [comment]
Updated compatibility version.
New plugin will be available shortly.
