### ISSUE TITLE
Question: All processed/generated locally

### ISSUE THREAD

**Issue by Auto81** [TSergey/intellij-javadocs#122]
More to get confirmation as I don't see any mention of it in documentation.

Are all the JavaDoc snippets processed/generated locally? And don't go out to third party systems like GPT etc

Thanks

**Comment by TSergey** [comment]
All java docs are generated using predefined templates: https://github.com/TSergey/intellij-javadocs/blob/master/src/main/resources/templates.xml
It's done locally, without any help of 3-d party systems.
