### ISSUE TITLE
Documentation unclear as to purpose 

### ISSUE THREAD

**Issue by grimreaper** [TSergey/intellij-javadocs#76]
It is not possible to tell the value of the plugin from the website or README without installing it. In particular it is unclear how it differs from IntelliJ's "generate javadoc" intention. 

(to clarify: I am not saying this project isn't cool or useful; just saying it should be documented)

**Comment by XP1** [comment]
It prefills the Javadocs using templates. The built-in Javadocs generator doesn't prefill generic descriptions.

See the demo video here:
https://imgur.com/uKavruK
