### ISSUE TITLE
javadocs plugin is not available. cause: null 

### ISSUE THREAD

**Issue by iqiancheng** [TSergey/intellij-javadocs#94]
Intellij IDEA: 
IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 15, 2020
Licensed to IntelliJ IDEA Evaluator
Expiration date: December 17, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4

javaDocs plugin version : latest version 

![image](https://user-images.githubusercontent.com/8328894/99945551-c86c4e80-2daf-11eb-8130-1036e4107e53.png)

```
Javadocs plugin is not available.
cause: null
```

**Comment by HoverCatz** [comment]
Same.

**Comment by kjv007** [comment]
yeah

**Comment by Pandu-Simbhothu** [comment]
Is this issue resolved?

**Comment by y0f0** [comment]
same
